### ISSUE TITLE
The difference between llama.cpp-dotnet and LLamaSharp?

### ISSUE THREAD

**Issue by yakovw** [dranger003/llama.cpp-dotnet#6]
I would very much like to know what are the advantages of the library llama.cpp-dotnet? I see that you put a lot of effort, I would love to know what additions there are in this library.
thanks a lot

**Comment by dranger003** [comment]
Thanks for the interest! While these projects may be sharing some functionality and capabilities, LlamaSharp is larger effort compared to this project. I am focusing on keeping the code as lean as possible as the main objective lies in learning more about LLMs using dotnet and C#, rather than create a featureful solution. Hope that makes sense.

**Comment by yakovw** [comment]
First thanks for the response.
If I understand you are saying that this is a project more for learning purposes, to get to know the world of LLM in C#?
If so, this is a very interesting idea
